tests/test_checkout.py::checkout_Test::test_checkout_unsuccessful_lastnameblank
--------------------------------------------------------------------
Last Page: [WARNING! Browser Not Open!]
 Duration: 5.14s
  Browser: Firefox 109.0 / headless
   Driver: geckodriver 0.32.0
Timestamp: 1675175260  (Unix Timestamp)
     Date: Tuesday, 31 January 2023
     Time: 2:27:40 PM  (UTC, UTC+00)
--------------------------------------------------------------------
Traceback: File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/runner/work/pfd_asg2_test/pfd_asg2_test/tests/test_checkout.py", line 49, in test_checkout_unsuccessful_lastnameblank
    self.save_screenshot_to_logs()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/seleniumbase/fixtures/base_case.py", line 3580, in save_screenshot_to_logs
    self.wait_for_ready_state_complete()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/seleniumbase/fixtures/base_case.py", line 3723, in wait_for_ready_state_complete
    self.__check_browser()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/seleniumbase/fixtures/base_case.py", line 11803, in __check_browser
    raise NoSuchWindowException("Active window was already closed!")
Exception: Message: Active window was already closed!
